spring:
  application:
    name: auth
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/auth
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: testuser
    password: password


kakao:
  client_id: ${kakao.api}
  redirect_uri: http://localhost:8080/kakao/callback