spring:
  application:
    name: auth
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.username}
    password: ${db.password}